### ISSUE TITLE
Add compatibility with PHPUnit 10.*

### ISSUE THREAD

**Issue by majermi4** [zenstruck/browser#118]
Hi,

I've tried upgrading my project to PHPUnit 10.* today and ran into errors like this when running my tests: 
```
1) Sworp\Tests\MyTest:testSomething
Error: Interface "PHPUnit\Runner\BeforeFirstTestHook" not found

/Users/michalmajer/Projects/Sworp/hub/vendor/zenstruck/browser/src/Browser/Test/BrowserExtension.php:16
```

Looks like this is due to the BrowserExtension using these hooks:
```
use PHPUnit\Runner\AfterLastTestHook;
use PHPUnit\Runner\AfterTestErrorHook;
use PHPUnit\Runner\AfterTestFailureHook;
use PHPUnit\Runner\AfterTestHook;
use PHPUnit\Runner\BeforeFirstTestHook;
use PHPUnit\Runner\BeforeTestHook;
```

which have been [deprecated in PHPUnit 10](https://github.com/sebastianbergmann/phpunit/issues/4595) and replaced by a new event system. https://thephp.cc/presentations/phpunit-10-the-new-event-subsystem

**Comment by kbond** [comment]
Yep, I think we'll need a phpunit 10 specific subscriber.

**Comment by kbond** [comment]
https://localheinz.com/articles/2023/02/14/extending-phpunit-with-its-new-event-system/

**Comment by nikophil** [comment]
I was thinking symfony bridge was not compatible yet?

**Comment by kbond** [comment]
Correct, my plan was to wait until the bridge supports phpunit 10 before digging into this.

The bridge isn't required by browser so if someone wants to create a PR in the meantime, that'd be cool.

**Comment by ostrolucky** [comment]
Looks like bridge is compatible now https://github.com/symfony/symfony/commit/8b2fe339811d1a21d5b52a41251eb8857629bd5a

**Comment by benr77** [comment]
Hi Kevin. Is there anything in the pipeline for PHPUnit 10 support yet? Thanks.

**Comment by kbond** [comment]
I'm still waiting for symfony/phpunit-bridge to support phpunit 10. I wouldn't use phpunit w/o the bridge so I don't have much motivation to implement yet.

**Comment by raneomik** [comment]
Hello,

I also bumped on this issue, and feeled free to inspire myself from what was done for Panther.

So here's my proposal for this issue : https://github.com/zenstruck/browser/pull/137

**Comment by Chris53897** [comment]
This can be closed as supported (with the linked PR).

**Comment by nikophil** [comment]
indeed, thanks!
