### ISSUE TITLE
document how to use when testing within a bundle

### ISSUE THREAD

**Issue by tacman** [zenstruck/browser#152]
I have a bundle that exposes a few controllers that I'm not sure how to test (from within the bundle).

https://github.com/symfony/symfony/discussions/57600#discussioncomment-9925933

Might that be possible with this library?  In particular, I'm not sure how to configure the routes, so that I can go to 

```php
$this->browser()
        ->visit('/my-bundle/admin')
        ->assertSuccessful()
```

Thanks.

**Comment by kbond** [comment]
We do this in [live components](https://github.com/symfony/ux/blob/2.x/src/LiveComponent/tests/Functional/LiveResponderTest.php). You basically have to setup a [test kernel](https://github.com/symfony/ux/blob/2.x/src/LiveComponent/tests/Fixtures/Kernel.php) for your bundle.

**Comment by tacman** [comment]
Thanks, I'll use LiveComponents as a model and work from there.
