### ISSUE TITLE
[PantherBrowser vs Browser][DAMA Extension Database]

### ISSUE THREAD

**Issue by GrinWay** [zenstruck/browser#161]
Imagine that you have DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension extension and 2 same tests that use PantherBrowser and Browser.
I noticed that there's a difference in behaviour of my tests when I use PantherBrowser and Browser.

The difference:
Using PantherBrowser: I can't load any data (event with the native for Doctrine EntityManagerInterface)
Using Browser: I CAN load any data

I came to the conclusion that if I use your bundle I don't have to use DAMA Extension

**Comment by kbond** [comment]
Correct, tests using panther browser cannot use dama. Panther requires a separate php process. This separate process won't see the same data as it's in-memory in the first process.

A solution could be two test suites: one that uses kernelbrowser and dama and one that uses pantherbrowser and no dama.
