### ISSUE TITLE
Add login() method

### ISSUE THREAD

**Issue by wouterj** [zenstruck/browser#18]
In Symfony 5.1, we added a way to login in tests: https://symfony.com/blog/new-in-symfony-5-1-simpler-login-in-tests

It would be great if we can port the same functionality to browser.

```php
$user = UserFactory::new()->create(['username' => 'john_user', 'password' => 'kitten']);

$this->kernelBrowser()
    ->loginAs($user)
    ->visit('/profile')
    // ...
;
```

**Comment by kbond** [comment]
See https://github.com/zenstruck/browser/blob/bfdb67a0698e6a848f0c0581dab69729f4859c1b/src/Browser/KernelBrowser.php#L84

I chose "actingAs" because it isn't a "real" login more of an impersonation. Laravel also uses this term.

**Comment by wouterj** [comment]
Sorry, turns out I'm bad and reading the README. I did a lazy search for `login`, which only gave me https://github.com/zenstruck/browser#authentication-extension

`actingAs()` works like a charm
