### ISSUE TITLE
[Suggestion] Throw exception if using assertRedirectedTo() without interceptRedirect()

### ISSUE THREAD

**Issue by wouterj** [zenstruck/browser#20]
I'm not sure if this is doable, as it seems like `interceptRedirect()` is a KernelBrowser feature, while `assertRedirectTo()` is a shared feature. However, I do think it's nice for DX if an error is thrown when asserting a redirection URL if it's followed (or somehow allow this assertion to work when following redirections).

**Comment by kbond** [comment]
BTW `interceptRedirects()`, `assertRedirected()` and `assertRedirectedTo()` are `KernelBrowser` and `HttpBrowser` *only* features.

This would indeed be helpful. `assertRedirected()` should get the error thrown as well.

**Comment by wouterj** [comment]
Ah, I think you can merge the `Http` trait in `BrowserKitBrowser` directly (I thought its features were reused, but seems like `BrowserKitBrowser` is the only one using that trait).
