### ISSUE TITLE
Use assertRedirectedTo without interceptRedirects 

### ISSUE THREAD

**Issue by Nyholm** [zenstruck/browser#24]
I just found something that was a bit weird. 

```php
        $this->kernelBrowser()
            ->actingAs(AuthenticatedUserFactory::fromCandidate($candidate), 'default')
            ->visit(\sprintf('/candidate/applications/%s/name', $application->getUuid()))
            ->assertStatus(200)
            ->assertSeeElement('#add_name_firstName')
            ->fillField('add_name_firstName', 'Test')
            ->fillField('add_name_lastName', 'Testsson')
            ->fillField('add_name_phoneNumber', '0123456789')
            ->click('add_name_submit')
            ->assertRedirectedTo(\sprintf('/candidate/applications/%s/background', $application->getUuid()));
```

This will not work because when I submit the form, there is a 302 and then a page that answer 200. Since Im not using `interceptRedirects()`, Browser will never see the 302 and the test will fail.

A simple workaround for me is just to add `->interceptRedirects()`. Im not sure any changes are needed, I just wanted to share my experience.

**Comment by kbond** [comment]
If I understand correctly, this should help: https://github.com/zenstruck/browser/commit/e1df6a9018246089600fa549077683db271f70af

When trying to assert redirected, an exception is thrown if not intercepting redirects.

**Comment by kbond** [comment]
Also see https://github.com/zenstruck/browser/issues/20

**Comment by Nyholm** [comment]
You are correct. THank you
