### ISSUE TITLE
Make Browser::response() public

### ISSUE THREAD

**Issue by Nyholm** [zenstruck/browser#4]
Is there any way that I can get the response?

Example: 

```php
         $json = $this->browser()
            ->get('/api/foo')
            ->assertStatus(200)
            ->myJsonOutput();

         $this->browser()
            ->get('/api/'.$json['my-key'])
            ->assertStatus(200);
``` 

But also, I may feel more comfortable running assertions on my body like I normally would... Or if my body is XML..

**Comment by Nyholm** [comment]
I could do like this: 

```php
$response = $this->browser()
    ->get('/api/foo')
    ->assertStatus(200)
    ->assertJson();
    ->inner()->getResponse();

$json = json_decode($response->getContent(), true);
```

I assume that the `$response` is different depending on what Browser Im using, right?

**Comment by kbond** [comment]
Yes, you're comment shows how to get the BrowserKit response but you're right, this is not available when using the `PantherBrowser`.

I do have a ["zenstruck/browser" specific response](https://github.com/zenstruck/browser/blob/1.x/src/Browser/Response.php) object that is used internally. It could provide what you're looking for (even with panther) but may be confusing as it is "yet another response object" (so it is currently not part of the public api).

If we made the internal response part of the public api, your code could look as follows:

```php
$response = $this->browser()
    ->get('/api/foo')
    ->assertStatus(200)
    ->assertJson();
    ->response() // because the content-type is json, this is an instance of \Zenstruck\Browser\Response\JsonResponse
;

$json = $response->json(); // this json_decodes the raw response body
```

**Comment by wouterj** [comment]
I think `->response()` would be nice. We don't have to tell people about the BrowserKit response I think, so this hopefully won't be too confusing.

I suggest also adding a `->crawler()` method to the response, to allow assertions on XML responses. It's currently quite a job to make a simple assertion:

```php
$response = $this->kernelBrowser()
    ->get('/en/blog/rss.xml')
    ->assertHeaderEquals('Content-Type', 'text/xml; charset=UTF-8')
    ->inner()->getResponse()
;

$dom = new \DOMDocument();
$dom->loadXML($response->getContent());
$crawler = new Crawler($dom);

$this->assertCount(Paginator::PAGE_SIZE, $crawler->filter('item'), 'The xml file displays the right number of posts.');
```

(or introduce an `XmlResponse`, as Mink explicitly only supports HTML responses. Not sure if XML responses are common enough to have built-in support)

**Comment by kbond** [comment]
I'd be fine with an `XmlResponse` - testing rss feeds & sitemaps is common enough I think.

For the `Response::crawler()` method:

1. Should this exist on the base response class? `JsonResponse` doesn't support this... but not adding hurts auto-completion. Throw exception when being called on `JsonResponse`?
2. Panther's crawler has some differences with the standard crawler and can't be used the same way. Should `PantherResponse::crawler()` return the standard crawler (built using the raw html of the response)?

**Comment by kbond** [comment]
Instead of making `Browser::response()` public, what about just adding a public `Browser::crawler(): Crawler` method? Would that suffice? I could also add a `Browser::json()` method to return the decoded response content.

The response is mostly an internal helper and adding yet another user land `Response` object would probably be confusing. WDYT?

**Comment by wouterj** [comment]
Works for me :+1:

**Comment by kbond** [comment]
Couldn't decide on the best course so I created 2 PRs that allow access to the crawler:

#27: makes `Browser::response()` public (marking many methods internal)
#28: adds `Browser::crawler()` keeping the `Response` an internal class

The readme changes in both PRs show the API's for each.

**Comment by Nyholm** [comment]
I think I like #27 more. But that is basically because I feel: "I just want to get the actually data, Dont give me a bunch of DTOs and helper objects."

**Comment by kbond** [comment]
I prefer #27 as well - the "browser" doesn't have a crawler, the browser's "current response" does.

**Comment by kbond** [comment]
I've (finally) decided to go with #27. Apologies for the delay.
