### ISSUE TITLE
assertSuccessfull for pantherBrowser

### ISSUE THREAD

**Issue by cadot-info** [zenstruck/browser#63]
I have read the README, it says
`  public function test_using_kernel_browser(): void
    {
        $this->browser()
            ->visit('/my/page')
            ->assertSuccessful()
        ;
    }
    
    /**
     * Requires this test extend Symfony\Component\Panther\PantherTestCase.
     */
    public function test_using_panther_browser(): void
    {
        $this->pantherBrowser()
            ->visit('/my/page')
            ->assertSuccessful()
        ;
    }`
but if i test with pantherbrowser i have this error:
`1) App\Tests\HomeControllerTest::testSomething
Error: Call to undefined method Zenstruck\Browser\PantherBrowser::assertSuccessful()
`
I have read src/Browser/PantherBrowser.php and Browser.php
and i has not AssertSuccessfull.

**Comment by kbond** [comment]
Hey! Yes, that is indeed a typo in the docs - I'll get that fixed.

For reference, Panther does not have access to the response status code so that's why that method is not available on `PantherBrowser`.

**Comment by cadot-info** [comment]
yes, i know this ;-)
thanks for your fast response and your good job.
