### ISSUE TITLE
Info: Cannot construct KeyEvent from non-typeable key (Problems with Keyboard-Layout)

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/browser#66]
This problem is not related to this repo.
But i hope it will be useful for other users.

I found a problem after i started to test an E-Mail-Field at start useing the "@" -Char.
`Facebook\WebDriver\Exception\UnknownErrorException : unknown error: Cannot construct KeyEvent from non-typeable key
  (Session info: chrome=98.0.4758.80)`

Google found this Issue.
https://groups.google.com/g/chromedriver-users/c/8WTsbereIO4

My Test-Environment is Mac M1 with Chrome 98 and the driver installed via Homebrew. Non English Keyboard Layout

**A temporary fix is to add english as keyboard language and switch to it.**
Now tests will run fine.

**Comment by thir13en** [comment]
Using Linux Fedora 34 here.

Added English as system and browser language and still having the error when trying to run a Java Selenium test where I send an email and password to an input.

**Comment by Chris53897** [comment]
@thir13en You have to switch the keyboard mapping to english to get it working.

**Comment by kbond** [comment]
Thanks for documenting this problem @Chris53897.

> You have to switch the keyboard mapping to english to get it working.

Can you explain how to do this?

**Comment by Chris53897** [comment]
Maybe **keyboard language** is the better english term. I found these tutorials to change it.
[Mac](https://www.digitalcitizen.life/change-keyboard-input-language-mac/)
[Gnome](https://help.gnome.org/users/gnome-help/stable/keyboard-layouts.html.en)

**Comment by Chris53897** [comment]
Today the fix for homebrew is released and the workaround is not needed anymore.
chromedriver 98.0.4758.80 -> 98.0.4758.102

This Issue could be closed. Maybe at the end of the month. (So people who have not the newest version can find the solution with the upgrade)
